### ISSUE TITLE
May I ask how to use your bible-plan-generator?

### ISSUE THREAD

**Issue by eliranwong** [mskelton/bible-plan-generator#1]
May I ask how to use your bible-plan-generator?

I don't find any instructions about its usage.

appreciate if you can give me some directions.  thanks in advance.

**Comment by mskelton** [comment]
It's been a while since I created and used this repo, but the steps are something like this:

1. Clone the repo
1. Create a token here: https://trello.com/app-key
1. Copy `config/secrets_example.json` to `config/secrets.json` and fill in the values
1. Run `python3 lib/bible.py` which should create a new board called Bible Reading Plan.

Hope that helps, let me know if it works!

**Comment by eliranwong** [comment]
Thanks for reply.  I didn't realise it needs to create an online account.  I though creating a bible reading plain could be offline.

I am looking for a bible reading plan utility that I may integrate with a bible software https://github.com/eliranwong/UniqueBible as a plugin.  It would be better if users do not need to to extra step to register an online account.

I am not ready to register an account in trello.  I may try later.  Is it possible to use your tool to generate a reading plan without using trello?

many thanks.

**Comment by mskelton** [comment]
This repo is designed specifically for Trello, so it wouldn't work for your use case.  Hope you find something that works though!
